version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: ${PROJECT_NAME}_redis
    restart: always
    ports:
      - ${EXPOSE_REDIS_PORT}:6379
    networks:
      - internal-network
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - 'redis_vol:/data'

  postgres:
    image: docker.io/bitnami/postgresql:16
    hostname: postgres
    container_name: ${PROJECT_NAME}_postgres
    restart: always
    ports:
      - ${EXPOSE_PG_PORT}:5432
    volumes:
      - 'postgres_vol:/bitnami/postgresql'
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - internal-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
    container_name: ${PROJECT_NAME}_elasticsearch
    hostname: elasticsearch
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch_vol:/usr/share/elasticsearch/data
    ports:
      - ${EXPOSE_ES_PORT_9200}:9200
      - ${EXPOSE_ES_PORT_9300}:9300
    networks:
      - internal-network
    env_file:
      - ./.env
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      discovery.type: single-node
    restart: unless-stopped

  webserver:
    build:
      context: ../
      dockerfile: Dockerfile
    hostname: webserver
    container_name: ${PROJECT_NAME}_webserver
    depends_on:
      - redis
      - postgres
      - elasticsearch
    networks:
      - internal-network
    volumes:
      - '../logs:/code/logs'
    env_file:
      - ../.env
    restart: always

  nginx:
    image: docker.io/bitnami/nginx:1.25
    hostname: nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${EXPOSE_NGINX_PORT}:8080
    depends_on:
      - webserver
    networks:
      - internal-network
    volumes:
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
      - ./nginx/server_blocks:/opt/bitnami/nginx/conf/server_blocks
      - nginx_vol:/opt/bitnami/nginx/logs
    restart: always

networks:
  internal-network:
    driver: bridge

volumes:
  postgres_vol:
    driver: local
    name: ${PROJECT_NAME}_postgres_vol
    driver_opts:
      type: none
      device: ${VOLUME_PATH_PG}
      o: bind

  elasticsearch_vol:
    driver: local
    name: ${PROJECT_NAME}_elasticsearch_vol
    driver_opts:
      type: none
      device: ${VOLUME_PATH_ES}
      o: bind

  redis_vol:
    driver: local
    name: ${PROJECT_NAME}_redis_vol
    driver_opts:
      type: none
      device: ${VOLUME_PATH_REDIS}
      o: bind

  nginx_vol:
    driver: local
    name: ${PROJECT_NAME}_nginx_vol
    driver_opts:
      type: none
      device: ${VOLUME_PATH_NGINX}
      o: bind

  pgbackups_vol:
    driver: local
    name: ${PROJECT_NAME}_pgbackups_vol
    driver_opts:
      type: none
      device: ${VOLUME_PATH_PG_BACKUP}
      o: bind
