name: filebeat

setup.ilm.enabled: false
setup.template.overwrite: true

setup.template:
  name: "filebeat-dgm_processing"
  pattern: "filebeat-dgm_processing-*"
  enabled: false

filebeat.inputs:

- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - /opt/logs/*.log

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata: ~
- decode_json_fields:
    fields: ["message"]
    process_array: false
    max_depth: 2
    target: ""
    overwrite_keys: true
    add_error_key: false

output.elasticsearch:
  hosts: [ http://192.168.1.219:9200 ]
  username: filebeat_internal
  password: '${FILEBEAT_INTERNAL_PASSWORD:}'
  index: "filebeat-dgm_processing-%{+yyyy.MM.dd}"