version: '3.8'

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    hostname: nfs-server
    container_name: nfs-server
    ports:
      - '2049:2049'
    volumes:
      - /opt/nfs/volumes:/nfs/share:rw
    environment:
      SHARED_DIRECTORY: /nfs/share
